//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Scripts
{
    [Serializable]
    public class TrackingStateResponse : Message
    {
        public const string k_RosMessageName = "Scripts/TrackingState";
        public override string RosMessageName => k_RosMessageName;

        public bool response;

        public TrackingStateResponse()
        {
            this.response = false;
        }

        public TrackingStateResponse(bool response)
        {
            this.response = response;
        }

        public static TrackingStateResponse Deserialize(MessageDeserializer deserializer) => new TrackingStateResponse(deserializer);

        private TrackingStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.response);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "TrackingStateResponse: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
