//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Scripts
{
    [Serializable]
    public class UpdatePositionRequest : Message
    {
        public const string k_RosMessageName = "Scripts/UpdatePosition";
        public override string RosMessageName => k_RosMessageName;

        public bool request;

        public UpdatePositionRequest()
        {
            this.request = false;
        }

        public UpdatePositionRequest(bool request)
        {
            this.request = request;
        }

        public static UpdatePositionRequest Deserialize(MessageDeserializer deserializer) => new UpdatePositionRequest(deserializer);

        private UpdatePositionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.request);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request);
        }

        public override string ToString()
        {
            return "UpdatePositionRequest: " +
            "\nrequest: " + request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
